# Generated by Django 5.2.5 on 2025-09-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industry",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
