# Generated by Django 5.2.5 on 2025-09-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_alter_industry_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="public_date",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
