# Generated by Django 5.2.5 on 2025-09-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_report", models.IntegerField(help_text="Năm")),
                ("length_report", models.IntegerField(help_text="Kỳ")),
                (
                    "total_assets",
                    models.BigIntegerField(
                        blank=True, help_text="TỔNG CỘNG TÀI SẢN (đồng)", null=True
                    ),
                ),
                (
                    "cash_and_cash_equivalents",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Tiền và tương đương tiền (đồng)",
                        null=True,
                    ),
                ),
                (
                    "balances_with_the_sbv",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Tiền gửi tại ngân hàng nhà nước Việt Nam",
                        null=True,
                    ),
                ),
                (
                    "placements_with_and_loans_to_other_credit_institutions",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Tiền gửi tại các TCTD khác và cho vay các TCTD khác",
                        null=True,
                    ),
                ),
                (
                    "trading_securities_net",
                    models.BigIntegerField(
                        blank=True, help_text="Chứng khoán kinh doanh thuần", null=True
                    ),
                ),
                (
                    "trading_securities",
                    models.BigIntegerField(
                        blank=True, help_text="Chứng khoán kinh doanh", null=True
                    ),
                ),
                (
                    "provision_for_diminution_in_value_of_trading_securities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Dự phòng giảm giá chứng khoán kinh doanh",
                        null=True,
                    ),
                ),
                (
                    "derivatives_and_other_financial_liabilities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Các công cụ tài chính phái sinh và khoản nợ tài chính khác",
                        null=True,
                    ),
                ),
                (
                    "loans_and_advances_to_customers_net",
                    models.BigIntegerField(
                        blank=True, help_text="Cho vay khách hàng thuần", null=True
                    ),
                ),
                (
                    "loans_and_advances_to_customers",
                    models.BigIntegerField(
                        blank=True, help_text="Cho vay khách hàng", null=True
                    ),
                ),
                (
                    "less_provision_for_losses_on_loans_and_advances_to_customers",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Dự phòng rủi ro cho vay khách hàng",
                        null=True,
                    ),
                ),
                (
                    "investment_securities",
                    models.BigIntegerField(
                        blank=True, help_text="Chứng khoán đầu tư", null=True
                    ),
                ),
                (
                    "available_for_sales_securities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Chứng khoán đầu tư sẵn sàng để bán",
                        null=True,
                    ),
                ),
                (
                    "held_to_maturity_securities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Chứng khoán đầu tư giữ đến ngày đáo hạn",
                        null=True,
                    ),
                ),
                (
                    "less_provision_for_diminution_in_value_of_investment_securities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Dự phòng giảm giá chứng khoán đầu tư",
                        null=True,
                    ),
                ),
                (
                    "long_term_investments",
                    models.BigIntegerField(
                        blank=True, help_text="Đầu tư dài hạn (đồng)", null=True
                    ),
                ),
                (
                    "investment_in_joint_ventures",
                    models.BigIntegerField(
                        blank=True, help_text="Đầu tư vào công ty con", null=True
                    ),
                ),
                (
                    "investments_in_associate_companies",
                    models.BigIntegerField(
                        blank=True, help_text="Đầu tư vào công ty liên doanh", null=True
                    ),
                ),
                (
                    "other_long_term_assets",
                    models.BigIntegerField(
                        blank=True, help_text="Tài sản dài hạn khác (đồng)", null=True
                    ),
                ),
                (
                    "less_provision_for_diminution_in_value_of_long_term_investments",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Dự phòng giảm giá đầu tư dài hạn",
                        null=True,
                    ),
                ),
                (
                    "fixed_assets",
                    models.BigIntegerField(
                        blank=True, help_text="Tài sản cố định (đồng)", null=True
                    ),
                ),
                (
                    "tangible_fixed_assets",
                    models.BigIntegerField(
                        blank=True, help_text="Tài sản cố định hữu hình", null=True
                    ),
                ),
                (
                    "intangible_fixed_assets",
                    models.BigIntegerField(
                        blank=True, help_text="Tài sản cố định vô hình", null=True
                    ),
                ),
                (
                    "other_assets",
                    models.BigIntegerField(
                        blank=True, help_text="Tài sản Có khác", null=True
                    ),
                ),
                (
                    "total_resources",
                    models.BigIntegerField(
                        blank=True, help_text="TỔNG CỘNG NGUỒN VỐN (đồng)", null=True
                    ),
                ),
                (
                    "liabilities",
                    models.BigIntegerField(
                        blank=True, help_text="NỢ PHẢI TRẢ (đồng)", null=True
                    ),
                ),
                (
                    "due_to_gov_and_borrowings_from_sbv",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Các khoản nợ chính phủ và NHNN Việt Nam",
                        null=True,
                    ),
                ),
                (
                    "deposits_and_borrowings_from_other_credit_institutions",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Tiền gửi và vay các Tổ chức tín dụng khác",
                        null=True,
                    ),
                ),
                (
                    "deposits_from_customers",
                    models.BigIntegerField(
                        blank=True, help_text="Tiền gửi của khách hàng", null=True
                    ),
                ),
                (
                    "derivatives_and_other_financial_liabilities_2",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Các công cụ tài chính phái sinh và khoản nợ tài chính khác",
                        null=True,
                    ),
                ),
                (
                    "funds_received_from_gov_international_and_other_institutions",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Vốn tài trợ, uỷ thác đầu tư của CP và các tổ chức TD khác",
                        null=True,
                    ),
                ),
                (
                    "convertible_bonds_cds_and_other_valuable_papers_issued",
                    models.BigIntegerField(
                        blank=True, help_text="Phát hành giấy tờ có giá", null=True
                    ),
                ),
                (
                    "other_liabilities",
                    models.BigIntegerField(
                        blank=True, help_text="Các khoản nợ khác", null=True
                    ),
                ),
                (
                    "owners_equity",
                    models.BigIntegerField(
                        blank=True, help_text="VỐN CHỦ SỞ HỮU (đồng)", null=True
                    ),
                ),
                (
                    "capital",
                    models.BigIntegerField(
                        blank=True, help_text="Vốn của tổ chức tín dụng", null=True
                    ),
                ),
                (
                    "reserves",
                    models.BigIntegerField(
                        blank=True, help_text="Quỹ của tổ chức tín dụng", null=True
                    ),
                ),
                (
                    "foreign_currency_difference_reserve",
                    models.BigIntegerField(
                        blank=True, help_text="Chênh lệch tỷ giá hối đoái", null=True
                    ),
                ),
                (
                    "difference_upon_assets_revaluation",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Chênh lệch đánh giá lại tài sản",
                        null=True,
                    ),
                ),
                (
                    "undistributed_earnings",
                    models.BigIntegerField(
                        blank=True, help_text="Lãi chưa phân phối (đồng)", null=True
                    ),
                ),
                (
                    "minority_interest",
                    models.BigIntegerField(
                        blank=True, help_text="Cổ đông thiểu số", null=True
                    ),
                ),
                (
                    "paid_in_capital",
                    models.BigIntegerField(
                        blank=True, help_text="Vốn góp của chủ sở hữu (đồng)", null=True
                    ),
                ),
                (
                    "other_reserves",
                    models.BigIntegerField(
                        blank=True, help_text="Các quỹ khác", null=True
                    ),
                ),
                (
                    "minority_interests",
                    models.BigIntegerField(
                        blank=True, help_text="LỢI ÍCH CỦA CỔ ĐÔNG THIỂU SỐ", null=True
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_sheets",
                        to="stock.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["-year_report", "-length_report"],
                "unique_together": {("symbol", "year_report", "length_report")},
            },
        ),
        migrations.CreateModel(
            name="CashFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_report", models.IntegerField(help_text="Năm")),
                ("length_report", models.IntegerField(help_text="Kỳ")),
                (
                    "profits_from_other_activities",
                    models.BigIntegerField(
                        blank=True, help_text="(Lãi)/lỗ các hoạt động khác", null=True
                    ),
                ),
                (
                    "operating_profit_before_changes_in_working_capital",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Lưu chuyển tiền thuần từ HĐKD trước thay đổi VLĐ",
                        null=True,
                    ),
                ),
                (
                    "net_cash_flows_from_operating_activities_before_bit",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Lưu chuyển tiền thuần từ HĐKD trước thuế",
                        null=True,
                    ),
                ),
                (
                    "payment_from_reserves",
                    models.BigIntegerField(
                        blank=True, help_text="Chi từ các quỹ của TCTD", null=True
                    ),
                ),
                (
                    "purchase_of_fixed_assets",
                    models.BigIntegerField(
                        blank=True, help_text="Mua sắm TSCĐ", null=True
                    ),
                ),
                (
                    "gain_on_dividend",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Tiền thu cổ tức và lợi nhuận được chia",
                        null=True,
                    ),
                ),
                (
                    "net_cash_flows_from_investing_activities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Lưu chuyển từ hoạt động đầu tư",
                        null=True,
                    ),
                ),
                (
                    "increase_in_charter_captial",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Tăng vốn cổ phần từ góp vốn và/hoặc phát hành cổ phiếu",
                        null=True,
                    ),
                ),
                (
                    "cash_flows_from_financial_activities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Lưu chuyển tiền từ hoạt động tài chính",
                        null=True,
                    ),
                ),
                (
                    "net_increase_decrease_in_cash_and_cash_equivalents",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Lưu chuyển tiền thuần trong kỳ",
                        null=True,
                    ),
                ),
                (
                    "cash_and_cash_equivalents",
                    models.BigIntegerField(
                        blank=True, help_text="Tiền và tương đương tiền", null=True
                    ),
                ),
                (
                    "foreign_exchange_differences_adjustment",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Ảnh hưởng của chênh lệch tỷ giá",
                        null=True,
                    ),
                ),
                (
                    "cash_and_cash_equivalents_at_the_end_of_period",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Tiền và tương đương tiền cuối kỳ",
                        null=True,
                    ),
                ),
                (
                    "net_cash_inflows_outflows_from_operating_activities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Lưu chuyển tiền tệ ròng từ các hoạt động SXKD",
                        null=True,
                    ),
                ),
                (
                    "proceeds_from_disposal_of_fixed_assets",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Tiền thu được từ thanh lý tài sản cố định",
                        null=True,
                    ),
                ),
                (
                    "investment_in_other_entities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Đầu tư vào các doanh nghiệp khác",
                        null=True,
                    ),
                ),
                (
                    "proceeds_from_divestment_in_other_entities",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Tiền thu từ việc bán các khoản đầu tư vào doanh nghiệp khác",
                        null=True,
                    ),
                ),
                (
                    "dividends_paid",
                    models.BigIntegerField(
                        blank=True, help_text="Cổ tức đã trả", null=True
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_flows",
                        to="stock.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["-year_report", "-length_report"],
                "unique_together": {("symbol", "year_report", "length_report")},
            },
        ),
        migrations.CreateModel(
            name="IncomeStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_report", models.IntegerField(help_text="Năm")),
                ("length_report", models.IntegerField(help_text="Kỳ")),
                (
                    "revenue",
                    models.BigIntegerField(
                        blank=True, help_text="Doanh thu (đồng)", null=True
                    ),
                ),
                (
                    "revenue_yoy",
                    models.FloatField(
                        blank=True, help_text="Tăng trưởng doanh thu (%)", null=True
                    ),
                ),
                (
                    "attribute_to_parent_company",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Lợi nhuận sau thuế của Cổ đông công ty mẹ (đồng)",
                        null=True,
                    ),
                ),
                (
                    "attribute_to_parent_company_yoy",
                    models.FloatField(
                        blank=True, help_text="Tăng trưởng lợi nhuận (%)", null=True
                    ),
                ),
                (
                    "interest_and_similar_income",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Thu nhập lãi và các khoản tương tự",
                        null=True,
                    ),
                ),
                (
                    "interest_and_similar_expenses",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Chi phí lãi và các khoản tương tự",
                        null=True,
                    ),
                ),
                (
                    "net_interest_income",
                    models.BigIntegerField(
                        blank=True, help_text="Thu nhập lãi thuần", null=True
                    ),
                ),
                (
                    "fees_and_comission_income",
                    models.BigIntegerField(
                        blank=True, help_text="Thu nhập từ hoạt động dịch vụ", null=True
                    ),
                ),
                (
                    "fees_and_comission_expenses",
                    models.BigIntegerField(
                        blank=True, help_text="Chi phí hoạt động dịch vụ", null=True
                    ),
                ),
                (
                    "net_fee_and_commission_income",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Lãi thuần từ hoạt động dịch vụ",
                        null=True,
                    ),
                ),
                (
                    "net_gain_foreign_currency_and_gold_dealings",
                    models.BigIntegerField(
                        blank=True, help_text="Kinh doanh ngoại hối và vàng", null=True
                    ),
                ),
                (
                    "net_gain_trading_of_trading_securities",
                    models.BigIntegerField(
                        blank=True, help_text="Chứng khoán kinh doanh", null=True
                    ),
                ),
                (
                    "net_gain_disposal_of_investment_securities",
                    models.BigIntegerField(
                        blank=True, help_text="Chứng khoán đầu tư", null=True
                    ),
                ),
                (
                    "net_other_income",
                    models.BigIntegerField(
                        blank=True, help_text="Hoạt động khác", null=True
                    ),
                ),
                (
                    "other_expenses",
                    models.BigIntegerField(
                        blank=True, help_text="Chi phí hoạt động khác", null=True
                    ),
                ),
                (
                    "net_other_income_expenses",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Lãi/lỗ thuần từ hoạt động khác",
                        null=True,
                    ),
                ),
                (
                    "dividends_received",
                    models.BigIntegerField(
                        blank=True, help_text="Cố tức đã nhận", null=True
                    ),
                ),
                (
                    "total_operating_revenue",
                    models.BigIntegerField(
                        blank=True, help_text="Tổng thu nhập hoạt động", null=True
                    ),
                ),
                (
                    "general_admin_expenses",
                    models.BigIntegerField(
                        blank=True, help_text="Chi phí quản lý DN", null=True
                    ),
                ),
                (
                    "operating_profit_before_provision",
                    models.BigIntegerField(
                        blank=True, help_text="LN từ HĐKD trước CF dự phòng", null=True
                    ),
                ),
                (
                    "provision_for_credit_losses",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Chi phí dự phòng rủi ro tín dụng",
                        null=True,
                    ),
                ),
                (
                    "profit_before_tax",
                    models.BigIntegerField(
                        blank=True, help_text="LN trước thuế", null=True
                    ),
                ),
                (
                    "tax_for_the_year",
                    models.BigIntegerField(
                        blank=True, help_text="Thuế TNDN", null=True
                    ),
                ),
                (
                    "business_income_tax_current",
                    models.BigIntegerField(
                        blank=True, help_text="Chi phí thuế TNDN hiện hành", null=True
                    ),
                ),
                (
                    "business_income_tax_deferred",
                    models.BigIntegerField(
                        blank=True, help_text="Chi phí thuế TNDN hoãn lại", null=True
                    ),
                ),
                (
                    "minority_interest",
                    models.BigIntegerField(
                        blank=True, help_text="Cổ đông thiểu số", null=True
                    ),
                ),
                (
                    "net_profit_for_the_year",
                    models.BigIntegerField(
                        blank=True, help_text="Lợi nhuận thuần", null=True
                    ),
                ),
                (
                    "attributable_to_parent_company",
                    models.BigIntegerField(
                        blank=True, help_text="Cổ đông của Công ty mẹ", null=True
                    ),
                ),
                (
                    "eps_basis",
                    models.IntegerField(
                        blank=True, help_text="Lãi cơ bản trên cổ phiếu", null=True
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_statements",
                        to="stock.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["-year_report", "-length_report"],
                "unique_together": {("symbol", "year_report", "length_report")},
            },
        ),
        migrations.CreateModel(
            name="Ratio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_report", models.IntegerField(help_text="Năm")),
                ("length_report", models.IntegerField(help_text="Kỳ")),
                (
                    "debt_equity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Nợ/VCSH",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "fixed_asset_to_equity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="TSCĐ / Vốn CSH",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "owners_equity_charter_capital",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Vốn CSH/Vốn điều lệ",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "net_profit_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Biên lợi nhuận ròng (%)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="ROE (%)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "roic",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="ROIC (%)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "roa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="ROA (%)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Tỷ suất cổ tức (%)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "financial_leverage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Đòn bẩy tài chính",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "market_capital",
                    models.BigIntegerField(
                        blank=True, help_text="Vốn hóa (Tỷ đồng)", null=True
                    ),
                ),
                (
                    "outstanding_share",
                    models.BigIntegerField(
                        blank=True, help_text="Số CP lưu hành (Triệu CP)", null=True
                    ),
                ),
                (
                    "pe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="P/E",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "pb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="P/B",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "ps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="P/S",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "p_cash_flow",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="P/Cash Flow",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "eps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="EPS (VND)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "bvps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="BVPS (VND)",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratios",
                        to="stock.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["-year_report", "-length_report"],
                "unique_together": {("symbol", "year_report", "length_report")},
            },
        ),
    ]
