# Generated by Django 5.2.5 on 2025-09-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balancesheet",
            name="available_for_sales_securities",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="balances_with_the_sbv",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="capital",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="convertible_bonds_cds_and_other_valuable_papers_issued",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="deposits_and_borrowings_from_other_credit_institutions",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="deposits_from_customers",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="derivatives_and_other_financial_liabilities",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="derivatives_and_other_financial_liabilities_2",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="difference_upon_assets_revaluation",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="due_to_gov_and_borrowings_from_sbv",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="foreign_currency_difference_reserve",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="funds_received_from_gov_international_and_other_institutions",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="held_to_maturity_securities",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="intangible_fixed_assets",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="investment_in_joint_ventures",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="investment_securities",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="investments_in_associate_companies",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="less_provision_for_diminution_in_value_of_investment_securities",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="less_provision_for_diminution_in_value_of_long_term_investments",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="less_provision_for_losses_on_loans_and_advances_to_customers",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="loans_and_advances_to_customers",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="loans_and_advances_to_customers_net",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="minority_interest",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="minority_interests",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="other_assets",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="other_liabilities",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="other_reserves",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="placements_with_and_loans_to_other_credit_institutions",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="provision_for_diminution_in_value_of_trading_securities",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="reserves",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="tangible_fixed_assets",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="trading_securities",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="trading_securities_net",
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="accounts_receivable",
            field=models.BigIntegerField(
                blank=True, help_text="Các khoản phải thu (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="advances_from_customers",
            field=models.BigIntegerField(
                blank=True, help_text="Người mua trả tiền trước (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="capital_and_reserves",
            field=models.BigIntegerField(
                blank=True, help_text="Vốn và quỹ (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="common_shares",
            field=models.BigIntegerField(
                blank=True, help_text="Cổ phiếu phổ thông (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="current_assets",
            field=models.BigIntegerField(
                blank=True, help_text="TÀI SẢN NGẮN HẠN (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="current_liabilities",
            field=models.BigIntegerField(
                blank=True, help_text="Nợ ngắn hạn (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="investment_and_development_funds",
            field=models.BigIntegerField(
                blank=True, help_text="Quỹ đầu tư & phát triển (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="long_term_assets",
            field=models.BigIntegerField(
                blank=True, help_text="TÀI SẢN DÀI HẠN (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="long_term_borrowings",
            field=models.BigIntegerField(
                blank=True, help_text="Vay và nợ dài hạn (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="long_term_liabilities",
            field=models.BigIntegerField(
                blank=True, help_text="Nợ dài hạn (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="long_term_prepayments",
            field=models.BigIntegerField(
                blank=True, help_text="Chi phí trả trước dài hạn (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="long_term_trade_receivables",
            field=models.BigIntegerField(
                blank=True, help_text="Phải thu thương mại dài hạn (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="net_inventories",
            field=models.BigIntegerField(
                blank=True, help_text="Hàng tồn kho thuần (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="other_current_assets",
            field=models.BigIntegerField(
                blank=True, help_text="Tài sản ngắn hạn khác (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="other_long_term_receivables",
            field=models.BigIntegerField(
                blank=True, help_text="Các khoản phải thu dài hạn (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="prepayments_to_suppliers",
            field=models.BigIntegerField(
                blank=True, help_text="Trả trước cho người bán (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="short_term_borrowings",
            field=models.BigIntegerField(
                blank=True, help_text="Vay và nợ ngắn hạn (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="short_term_investments",
            field=models.BigIntegerField(
                blank=True, help_text="Đầu tư ngắn hạn (Bn. VND)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="cash_and_cash_equivalents",
            field=models.BigIntegerField(
                blank=True, help_text="Tiền và tương đương tiền (Bn. VND)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="fixed_assets",
            field=models.BigIntegerField(
                blank=True, help_text="Tài sản cố định (Bn. VND)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="length_report",
            field=models.IntegerField(help_text="Kỳ báo cáo (Q1, Q2, Q3, Q4, Năm)"),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="liabilities",
            field=models.BigIntegerField(
                blank=True, help_text="NỢ PHẢI TRẢ (Bn. VND)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="long_term_investments",
            field=models.BigIntegerField(
                blank=True, help_text="Đầu tư dài hạn (Bn. VND)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="other_long_term_assets",
            field=models.BigIntegerField(
                blank=True, help_text="Tài sản dài hạn khác (Bn. VND)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="owners_equity",
            field=models.BigIntegerField(
                blank=True, help_text="VỐN CHỦ SỞ HỮU (Bn. VND)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="paid_in_capital",
            field=models.BigIntegerField(
                blank=True, help_text="Vốn góp của chủ sở hữu (Bn. VND)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="total_assets",
            field=models.BigIntegerField(
                blank=True, help_text="TỔNG CỘNG TÀI SẢN (Bn. VND)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="total_resources",
            field=models.BigIntegerField(
                blank=True, help_text="TỔNG CỘNG NGUỒN VỐN (Bn. VND)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="undistributed_earnings",
            field=models.BigIntegerField(
                blank=True, help_text="Lãi chưa phân phối (Bn. VND)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="year_report",
            field=models.IntegerField(help_text="Năm báo cáo"),
        ),
    ]
