# Generated by Django 5.2.5 on 2025-09-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "calculate",
            "0002_remove_balancesheet_available_for_sales_securities_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balancesheet",
            name="accounts_receivable",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="advances_from_customers",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="capital_and_reserves",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="cash_and_cash_equivalents",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="common_shares",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="current_assets",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="current_liabilities",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="fixed_assets",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="investment_and_development_funds",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="liabilities",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="long_term_assets",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="long_term_borrowings",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="long_term_investments",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="long_term_liabilities",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="long_term_prepayments",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="long_term_trade_receivables",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="other_current_assets",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="other_long_term_assets",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="other_long_term_receivables",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="owners_equity",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="paid_in_capital",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="prepayments_to_suppliers",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="short_term_borrowings",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="short_term_investments",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="total_assets",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="total_resources",
        ),
        migrations.RemoveField(
            model_name="balancesheet",
            name="undistributed_earnings",
        ),
        migrations.RemoveField(
            model_name="cashflow",
            name="net_cash_flows_from_operating_activities_before_bit",
        ),
        migrations.RemoveField(
            model_name="cashflow",
            name="payment_from_reserves",
        ),
        migrations.RemoveField(
            model_name="cashflow",
            name="profits_from_other_activities",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="attribute_to_parent_company",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="attribute_to_parent_company_yoy",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="dividends_received",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="eps_basis",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="fees_and_comission_expenses",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="fees_and_comission_income",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="interest_and_similar_expenses",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="interest_and_similar_income",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="net_fee_and_commission_income",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="net_gain_disposal_of_investment_securities",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="net_gain_foreign_currency_and_gold_dealings",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="net_gain_trading_of_trading_securities",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="net_interest_income",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="net_other_income",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="operating_profit_before_provision",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="other_expenses",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="provision_for_credit_losses",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="revenue",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="revenue_yoy",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="tax_for_the_year",
        ),
        migrations.RemoveField(
            model_name="incomestatement",
            name="total_operating_revenue",
        ),
        migrations.RemoveField(
            model_name="ratio",
            name="bvps",
        ),
        migrations.RemoveField(
            model_name="ratio",
            name="dividend_yield",
        ),
        migrations.RemoveField(
            model_name="ratio",
            name="eps",
        ),
        migrations.RemoveField(
            model_name="ratio",
            name="market_capital",
        ),
        migrations.RemoveField(
            model_name="ratio",
            name="net_profit_margin",
        ),
        migrations.RemoveField(
            model_name="ratio",
            name="outstanding_share",
        ),
        migrations.RemoveField(
            model_name="ratio",
            name="pb",
        ),
        migrations.RemoveField(
            model_name="ratio",
            name="pe",
        ),
        migrations.RemoveField(
            model_name="ratio",
            name="ps",
        ),
        migrations.RemoveField(
            model_name="ratio",
            name="roa",
        ),
        migrations.RemoveField(
            model_name="ratio",
            name="roe",
        ),
        migrations.RemoveField(
            model_name="ratio",
            name="roic",
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="accounts_receivable_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="advances_from_customers_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="capital_and_reserves_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="cash_and_cash_equivalents_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="common_shares_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="current_assets_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="current_liabilities_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="fixed_assets_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="good_will_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="inventories_net_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="investment_and_development_funds_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="liabilities_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="long_term_assets_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="long_term_borrowings_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="long_term_investments_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="long_term_liabilities_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="long_term_loans_receivables_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="long_term_prepayments_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="long_term_trade_receivables_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="minority_interests",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="other_current_assets_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="other_long_term_assets_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="other_long_term_receivables_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="other_non_current_assets",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="owners_equitybn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="paid_in_capital_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="prepayments_to_suppliers_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="short_term_borrowings_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="short_term_investments_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="short_term_loans_receivables_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="total_assets_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="total_resources_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="undistributed_earnings_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="business_income_tax_paid",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="collection_loans_proceeds_sales_debts_instruments_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="depreciation_and_amortisation",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="finance_lease_principal_payments",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="increase_decrease_in_inventories",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="increase_decrease_in_payables",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="increase_decrease_in_prepaid_expenses",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="increase_decrease_in_receivables",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="interest_expense",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="interest_paid",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="loans_granted_purchases_of_debt_instruments_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="net_profit_loss_before_tax",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="payments_for_share_repurchases",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="proceeds_from_borrowings",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="profit_loss_from_investing_activities",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="provision_for_credit_losses",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="repayment_of_borrowings",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashflow",
            name="unrealized_foreign_exchange_gain_loss",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="attribute_to_parent_company_bn_vnd",
            field=models.BigIntegerField(
                blank=True, help_text="LN sau thuế CĐ công ty mẹ (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="attribute_to_parent_company_yo_y_percent",
            field=models.FloatField(
                blank=True, help_text="Tăng trưởng LN CĐ mẹ YoY (%)", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="cost_of_sales",
            field=models.BigIntegerField(
                blank=True, help_text="Giá vốn hàng bán", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="financial_expenses",
            field=models.BigIntegerField(
                blank=True, help_text="Chi phí tài chính", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="financial_income",
            field=models.BigIntegerField(
                blank=True, help_text="Thu nhập tài chính (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="gain_loss_from_joint_ventures",
            field=models.BigIntegerField(
                blank=True, help_text="LN/Lỗ liên doanh", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="gross_profit",
            field=models.BigIntegerField(
                blank=True, help_text="Lợi nhuận gộp", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="interest_expenses",
            field=models.BigIntegerField(
                blank=True, help_text="Chi phí lãi vay (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="net_sales",
            field=models.BigIntegerField(
                blank=True, help_text="Doanh thu thuần", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="operating_profit_loss",
            field=models.BigIntegerField(blank=True, help_text="LN từ HĐKD", null=True),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="other_income",
            field=models.BigIntegerField(
                blank=True, help_text="Thu nhập khác", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="other_income_expenses",
            field=models.BigIntegerField(
                blank=True, help_text="Thu nhập/Chi phí khác", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="revenue_bn_vnd",
            field=models.BigIntegerField(
                blank=True, help_text="Doanh thu (Bn. VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="revenue_yoy_percent",
            field=models.FloatField(
                blank=True, help_text="Doanh thu YoY (%)", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="sales",
            field=models.BigIntegerField(
                blank=True, help_text="Doanh thu bán hàng", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="sales_deductions",
            field=models.BigIntegerField(
                blank=True, help_text="Các khoản giảm trừ", null=True
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="selling_expenses",
            field=models.BigIntegerField(
                blank=True, help_text="Chi phí bán hàng", null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="asset_turnover",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="bvps_vnd",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="cash_cycle",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="cash_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="current_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="days_inventory_outstanding",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="days_payable_outstanding",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="days_sales_outstanding",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="dividend_yield_percent",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="ebit_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ratio",
            name="ebit_margin_percent",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="ebitda_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ratio",
            name="eps_vnd",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="ev_ebitda",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="fixed_asset_turnover",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="gross_profit_margin_percent",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="interest_coverage",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="inventory_turnover",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="market_capital_bn_vnd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ratio",
            name="net_profit_margin_percent",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="outstanding_share_mil_shares",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ratio",
            name="p_b",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="p_e",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="p_s",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="quick_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="roa_percent",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="roe_percent",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="roic_percent",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ratio",
            name="st_lt_borrowings_equity",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="length_report",
            field=models.IntegerField(help_text="Kỳ báo cáo"),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="net_inventories",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="cash_and_cash_equivalents",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="cash_and_cash_equivalents_at_the_end_of_period",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="cash_flows_from_financial_activities",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="dividends_paid",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="foreign_exchange_differences_adjustment",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="gain_on_dividend",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="increase_in_charter_captial",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="investment_in_other_entities",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="net_cash_flows_from_investing_activities",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="net_cash_inflows_outflows_from_operating_activities",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="net_increase_decrease_in_cash_and_cash_equivalents",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="operating_profit_before_changes_in_working_capital",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="proceeds_from_disposal_of_fixed_assets",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="proceeds_from_divestment_in_other_entities",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cashflow",
            name="purchase_of_fixed_assets",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incomestatement",
            name="attributable_to_parent_company",
            field=models.BigIntegerField(
                blank=True, help_text="LN thuộc về CĐ công ty mẹ", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incomestatement",
            name="business_income_tax_current",
            field=models.BigIntegerField(
                blank=True, help_text="Thuế TNDN hiện hành", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incomestatement",
            name="business_income_tax_deferred",
            field=models.BigIntegerField(
                blank=True, help_text="Thuế TNDN hoãn lại", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incomestatement",
            name="general_admin_expenses",
            field=models.BigIntegerField(
                blank=True, help_text="Chi phí QLDN", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incomestatement",
            name="minority_interest",
            field=models.BigIntegerField(
                blank=True, help_text="Lợi ích cổ đông thiểu số", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incomestatement",
            name="net_other_income_expenses",
            field=models.BigIntegerField(
                blank=True, help_text="LN/Lỗ thuần từ HĐ khác", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incomestatement",
            name="net_profit_for_the_year",
            field=models.BigIntegerField(
                blank=True, help_text="LN thuần năm", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ratio",
            name="debt_equity",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ratio",
            name="financial_leverage",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ratio",
            name="fixed_asset_to_equity",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ratio",
            name="length_report",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ratio",
            name="owners_equity_charter_capital",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ratio",
            name="p_cash_flow",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ratio",
            name="year_report",
            field=models.IntegerField(),
        ),
    ]
