# Generated by Django 5.2.5 on 2025-09-16 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calculate", "0003_remove_balancesheet_accounts_receivable_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cashflow",
            old_name="collection_loans_proceeds_sales_debts_instruments_vnd",
            new_name="collection_of_loans_proceeds_sales_instruments_vnd",
        ),
    ]
