# Generated by Django 5.2.6 on 2025-09-22 04:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seapay", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayBotOrder",
            fields=[
                (
                    "order_id",
                    models.UUIDField(
                        db_comment="ID đơn hàng",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        db_comment="Tổng tiền cần trả cho đơn",
                        decimal_places=2,
                        max_digits=18,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_comment="Trạng thái vòng đời đơn",
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wallet", "Wallet Balance"),
                            ("sepay_transfer", "SePay Transfer (QR/Bank)"),
                        ],
                        db_comment="wallet (trừ ví) hoặc sepay_transfer (QR/STK)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_comment="Mô tả/ghi chú đơn hàng", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pay_bot_orders",
                "db_table_comment": "Đơn hàng để mua bot. Có thể thanh toán trực tiếp qua SePay hoặc trừ ví nếu đã nạp.",
            },
        ),
        migrations.CreateModel(
            name="PayBotOrderItem",
            fields=[
                (
                    "order_item_id",
                    models.UUIDField(
                        db_comment="ID item đơn hàng",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "symbol_id",
                    models.BigIntegerField(db_comment="Symbol là sản phẩm được bán"),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_comment="Đơn giá tại thời điểm mua",
                        decimal_places=2,
                        max_digits=18,
                    ),
                ),
                (
                    "license_days",
                    models.IntegerField(
                        blank=True,
                        db_comment="Số ngày cấp quyền sử dụng bot; null = trọn đời",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        db_comment="Thuộc tính thêm (phiên bản bot, biến thể, ...)",
                        default=dict,
                    ),
                ),
            ],
            options={
                "db_table": "pay_bot_order_items",
                "db_table_comment": "Chi tiết từng dòng sản phẩm trong đơn: bot nào, thời hạn bao lâu.",
            },
        ),
        migrations.CreateModel(
            name="PayUserBotLicense",
            fields=[
                (
                    "license_id",
                    models.UUIDField(
                        db_comment="ID license",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol_id", models.BigIntegerField(db_comment="Bot được cấp quyền")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                        ],
                        db_comment="Trạng thái quyền dùng bot",
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        db_comment="Thời điểm kích hoạt",
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Thời điểm hết hạn; null = trọn đời",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pay_user_bot_licenses",
                "db_table_comment": "Quyền sử dụng bot để quyết định ai được nhận tín hiệu.",
            },
        ),
        migrations.AlterModelTableComment(
            name="paywalletledger",
            table_comment="Quy tắc: deposit phải có payment_id (SePay); purchase phải có order_id. Sổ cái là nguồn sự thật để tính balance.",
        ),
        migrations.RenameIndex(
            model_name="paywalletledger",
            new_name="idx_ledger_wallet_created",
            old_name="idx_wallet_ledger_wallet",
        ),
        migrations.RenameIndex(
            model_name="paywalletledger",
            new_name="idx_ledger_payment",
            old_name="idx_wallet_ledger_payment",
        ),
        migrations.RenameIndex(
            model_name="paywalletledger",
            new_name="idx_ledger_tx_type",
            old_name="idx_wallet_ledger_tx_type",
        ),
        migrations.RemoveField(
            model_name="paywalletledger",
            name="description",
        ),
        migrations.AddField(
            model_name="paywalletledger",
            name="note",
            field=models.TextField(
                blank=True, db_comment="Diễn giải ngắn gọn cho bản ghi sổ cái"
            ),
        ),
        migrations.AlterField(
            model_name="paywalletledger",
            name="amount",
            field=models.DecimalField(
                db_comment="Luôn > 0; chiều thể hiện bằng is_credit",
                decimal_places=2,
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="paywalletledger",
            name="balance_after",
            field=models.DecimalField(
                db_comment="Số dư ngay sau giao dịch này",
                decimal_places=2,
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="paywalletledger",
            name="is_credit",
            field=models.BooleanField(db_comment="true: cộng ví; false: trừ ví"),
        ),
        migrations.AlterField(
            model_name="paywalletledger",
            name="metadata",
            field=models.JSONField(
                blank=True,
                db_comment="Payload bổ sung: ip, device, source, ...",
                default=dict,
            ),
        ),
        migrations.AlterField(
            model_name="paywalletledger",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                db_comment="Bắt buộc với deposit (nạp qua SePay)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="seapay.paypayment",
            ),
        ),
        migrations.AlterField(
            model_name="paywalletledger",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Nạp tiền (từ SePay)"),
                    ("purchase", "Mua bot"),
                    ("refund", "Hoàn tiền"),
                    ("withdrawal", "Rút tiền"),
                    ("transfer_in", "Chuyển đến"),
                    ("transfer_out", "Chuyển đi"),
                ],
                db_comment="Loại biến động: nạp/purchase/hoàn tiền/...",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paybotorder",
            name="payment_intent",
            field=models.ForeignKey(
                blank=True,
                db_comment="Payment intent cho SePay transfer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="seapay.paypaymentintent",
            ),
        ),
        migrations.AddField(
            model_name="paybotorder",
            name="user",
            field=models.ForeignKey(
                db_comment="Người mua bot",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paywalletledger",
            name="order",
            field=models.ForeignKey(
                blank=True,
                db_comment="Liên kết đơn hàng khi là purchase/refund",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="seapay.paybotorder",
            ),
        ),
        migrations.AddIndex(
            model_name="paywalletledger",
            index=models.Index(fields=["order"], name="idx_ledger_order"),
        ),
        migrations.AddField(
            model_name="paybotorderitem",
            name="order",
            field=models.ForeignKey(
                db_comment="Đơn hàng chính",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="seapay.paybotorder",
            ),
        ),
        migrations.AddField(
            model_name="payuserbotlicense",
            name="order",
            field=models.ForeignKey(
                blank=True,
                db_comment="Đơn hàng tạo ra license này",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="seapay.paybotorder",
            ),
        ),
        migrations.AddField(
            model_name="payuserbotlicense",
            name="user",
            field=models.ForeignKey(
                db_comment="User được cấp quyền",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="paybotorder",
            index=models.Index(
                fields=["user", "status"], name="idx_bot_orders_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="paybotorder",
            index=models.Index(fields=["status"], name="idx_bot_orders_status"),
        ),
        migrations.AddIndex(
            model_name="paybotorder",
            index=models.Index(fields=["created_at"], name="idx_bot_orders_created"),
        ),
        migrations.AddIndex(
            model_name="paybotorderitem",
            index=models.Index(fields=["order"], name="idx_bot_order_items_order"),
        ),
        migrations.AddIndex(
            model_name="paybotorderitem",
            index=models.Index(fields=["symbol_id"], name="idx_bot_order_items_symbol"),
        ),
        migrations.AddIndex(
            model_name="payuserbotlicense",
            index=models.Index(
                fields=["user", "symbol_id"], name="idx_bot_licenses_user_symbol"
            ),
        ),
        migrations.AddIndex(
            model_name="payuserbotlicense",
            index=models.Index(fields=["status"], name="idx_bot_licenses_status"),
        ),
        migrations.AddIndex(
            model_name="payuserbotlicense",
            index=models.Index(fields=["end_at"], name="idx_bot_licenses_end_at"),
        ),
        migrations.AlterUniqueTogether(
            name="payuserbotlicense",
            unique_together={("user", "symbol_id", "start_at")},
        ),
    ]
