# Generated by Django 5.2.5 on 2025-09-19 02:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seapay", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seapayorder",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="seapayorder",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="seapayorder",
            name="description",
        ),
        migrations.RemoveField(
            model_name="seapayorder",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="seapayorder",
            name="qr_code_url",
        ),
        migrations.RemoveField(
            model_name="seapayorder",
            name="status",
        ),
        migrations.RemoveField(
            model_name="seapayorder",
            name="updated_at",
        ),
        migrations.CreateModel(
            name="PayWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        db_comment="Số dư hiện tại, chỉ cập nhật qua ledger",
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("VND", "Vietnamese Dong"), ("USD", "US Dollar")],
                        db_comment="Loại tiền (VNĐ, USD...)",
                        default="VND",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        db_comment="active | suspended (khóa tạm thời)",
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="Chủ ví",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "pay_wallets",
                "db_table_comment": "Mỗi user có 1 ví / 1 loại tiền. Tất cả thay đổi số dư đi qua pay_wallet_ledger.",
            },
        ),
        migrations.CreateModel(
            name="PayPaymentIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("sepay", "SePay")],
                        db_comment="Nhà cung cấp thanh toán (hiện tại chỉ SePay)",
                        default="sepay",
                        max_length=20,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("wallet_topup", "Wallet Top-up"),
                            ("order_payment", "Order Payment"),
                            ("withdraw", "Withdraw"),
                        ],
                        db_comment="wallet_topup | order_payment | withdraw",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_comment="Số tiền cần thanh toán",
                        decimal_places=2,
                        max_digits=18,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requires_payment_method", "Requires Payment Method"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        db_comment="requires_payment_method | processing | succeeded | failed | expired",
                        default="requires_payment_method",
                        max_length=30,
                    ),
                ),
                (
                    "order_code",
                    models.CharField(
                        db_comment="Chuỗi đối soát CK (nội dung chuyển khoản). Match với content từ SePay.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        db_comment="Mã tham chiếu từ SePay (referenceCode) để tránh trùng lặp giao dịch",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "return_url",
                    models.TextField(
                        blank=True,
                        db_comment="URL trở về khi thanh toán xong (webflow)",
                        null=True,
                    ),
                ),
                (
                    "cancel_url",
                    models.TextField(
                        blank=True, db_comment="URL trở về khi hủy", null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_comment="Hạn dùng intent/QR", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        db_comment="Payload bổ sung (IP, UA, campaign...)",
                        default=dict,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="Ai thực hiện thanh toán",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Ví bị ảnh hưởng (nếu là nạp tiền/rút tiền)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seapay.paywallet",
                    ),
                ),
            ],
            options={
                "db_table": "pay_payment_intents",
                "db_table_comment": "Intent thanh toán. order_code ~ content, reference_code ~ callback id từ SePay.",
            },
        ),
        migrations.AddIndex(
            model_name="paywallet",
            index=models.Index(fields=["user"], name="idx_pay_wallets_user"),
        ),
        migrations.AddConstraint(
            model_name="paywallet",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_wallet"
            ),
        ),
        migrations.AddIndex(
            model_name="paypaymentintent",
            index=models.Index(
                fields=["user", "status"], name="idx_pay_intents_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="paypaymentintent",
            index=models.Index(
                fields=["reference_code"], name="idx_pay_intents_reference"
            ),
        ),
        migrations.AddIndex(
            model_name="paypaymentintent",
            index=models.Index(
                fields=["order_code"], name="idx_pay_intents_order_code"
            ),
        ),
        migrations.AddIndex(
            model_name="paypaymentintent",
            index=models.Index(fields=["created_at"], name="idx_pay_intents_created"),
        ),
    ]
