# Generated by Django 5.2.5 on 2025-09-22 07:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seapay", "0002_paybotorder_paybotorderitem_payuserbotlicense_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paybotorder",
            name="payment_intent",
        ),
        migrations.RemoveField(
            model_name="paybotorder",
            name="user",
        ),
        migrations.RemoveField(
            model_name="payuserbotlicense",
            name="order",
        ),
        migrations.AlterUniqueTogether(
            name="payuserbotlicense",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="payuserbotlicense",
            name="user",
        ),
        migrations.CreateModel(
            name="PaySymbolOrder",
            fields=[
                (
                    "order_id",
                    models.UUIDField(
                        db_comment="ID đơn hàng",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        db_comment="Tổng tiền cần trả cho đơn",
                        decimal_places=2,
                        max_digits=18,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_comment="Trạng thái vòng đời đơn",
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wallet", "Wallet Balance"),
                            ("sepay_transfer", "SePay Transfer (QR/Bank)"),
                        ],
                        db_comment="wallet (trừ ví) hoặc sepay_transfer (QR/STK)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_comment="Mô tả/ghi chú đơn hàng", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_intent",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Payment intent cho SePay transfer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seapay.paypaymentintent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="Người mua quyền truy cập symbol",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pay_symbol_orders",
                "db_table_comment": "Đơn hàng để mua quyền truy cập symbol. Có thể thanh toán trực tiếp qua SePay hoặc trừ ví nếu đã nạp.",
            },
        ),
        migrations.AlterField(
            model_name="paypayment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                db_comment="Đơn hàng liên quan (nếu có)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="seapay.paysymbolorder",
            ),
        ),
        migrations.AlterField(
            model_name="paypaymentintent",
            name="order",
            field=models.ForeignKey(
                blank=True,
                db_comment="Liên kết nếu là thanh toán đơn",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="seapay.paysymbolorder",
            ),
        ),
        migrations.AlterField(
            model_name="paywalletledger",
            name="order",
            field=models.ForeignKey(
                blank=True,
                db_comment="Liên kết đơn hàng khi là purchase/refund",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="seapay.paysymbolorder",
            ),
        ),
        migrations.CreateModel(
            name="PaySymbolOrderItem",
            fields=[
                (
                    "order_item_id",
                    models.UUIDField(
                        db_comment="ID item đơn hàng",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "symbol_id",
                    models.BigIntegerField(db_comment="Symbol là sản phẩm được bán"),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_comment="Đơn giá tại thời điểm mua",
                        decimal_places=2,
                        max_digits=18,
                    ),
                ),
                (
                    "license_days",
                    models.IntegerField(
                        blank=True,
                        db_comment="Số ngày cấp quyền sử dụng symbol; null = trọn đời",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        db_comment="Thuộc tính thêm (phiên bản, biến thể, ...)",
                        default=dict,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_comment="Đơn hàng chính",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="seapay.paysymbolorder",
                    ),
                ),
            ],
            options={
                "db_table": "pay_symbol_order_items",
                "db_table_comment": "Chi tiết từng dòng sản phẩm trong đơn: symbol nào, thời hạn bao lâu.",
            },
        ),
        migrations.CreateModel(
            name="PayUserSymbolLicense",
            fields=[
                (
                    "license_id",
                    models.UUIDField(
                        db_comment="ID license",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "symbol_id",
                    models.BigIntegerField(db_comment="Symbol được cấp quyền"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                        ],
                        db_comment="Trạng thái quyền dùng symbol",
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        db_comment="Thời điểm kích hoạt",
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Thời điểm hết hạn; null = trọn đời",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Đơn hàng tạo ra license này",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="seapay.paysymbolorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="User được cấp quyền",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pay_user_symbol_licenses",
                "db_table_comment": "Quyền sử dụng symbol để quyết định ai được nhận tín hiệu.",
            },
        ),
        migrations.DeleteModel(
            name="PayBotOrderItem",
        ),
        migrations.DeleteModel(
            name="PayUserBotLicense",
        ),
        migrations.AddIndex(
            model_name="paysymbolorder",
            index=models.Index(
                fields=["user", "status"], name="idx_symbol_orders_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="paysymbolorder",
            index=models.Index(fields=["status"], name="idx_symbol_orders_status"),
        ),
        migrations.AddIndex(
            model_name="paysymbolorder",
            index=models.Index(fields=["created_at"], name="idx_symbol_orders_created"),
        ),
        migrations.DeleteModel(
            name="PayBotOrder",
        ),
        migrations.AddIndex(
            model_name="paysymbolorderitem",
            index=models.Index(fields=["order"], name="idx_symbol_order_items_order"),
        ),
        migrations.AddIndex(
            model_name="paysymbolorderitem",
            index=models.Index(
                fields=["symbol_id"], name="idx_symbol_order_items_symbol"
            ),
        ),
        migrations.AddIndex(
            model_name="payusersymbollicense",
            index=models.Index(
                fields=["user", "symbol_id"], name="idx_symbol_lic_user_symbol"
            ),
        ),
        migrations.AddIndex(
            model_name="payusersymbollicense",
            index=models.Index(fields=["status"], name="idx_symbol_lic_status"),
        ),
        migrations.AddIndex(
            model_name="payusersymbollicense",
            index=models.Index(fields=["end_at"], name="idx_symbol_lic_end_at"),
        ),
        migrations.AlterUniqueTogether(
            name="payusersymbollicense",
            unique_together={("user", "symbol_id", "start_at")},
        ),
    ]
