# Generated by Django 5.2.5 on 2025-09-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seapay", "0003_remove_paybotorder_payment_intent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paypaymentintent",
            name="deep_link",
            field=models.TextField(
                blank=True, db_comment="Deep link for mobile payment", null=True
            ),
        ),
        migrations.AddField(
            model_name="paypaymentintent",
            name="qr_code_url",
            field=models.TextField(
                blank=True, db_comment="QR code URL for payment", null=True
            ),
        ),
    ]
