# Generated by Django 5.2.5 on 2025-09-19 02:13

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(max_length=20)),
                ("channel", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("environment", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "logs",
                "indexes": [
                    models.Index(fields=["-created_at"], name="idx_logs_created_at"),
                    models.Index(fields=["level"], name="idx_logs_level"),
                    models.Index(fields=["channel"], name="idx_logs_channel"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["context"], name="idx_logs_context_gin"
                    ),
                ],
            },
        ),
    ]
