# Generated by Django 5.2.5 on 2025-09-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelTableComment(
            name="logentry",
            table_comment="System logs for auditing and debugging",
        ),
        migrations.AlterField(
            model_name="logentry",
            name="channel",
            field=models.CharField(
                db_comment="Log channel: app, queue, payment, web, etc.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="context",
            field=models.JSONField(
                blank=True,
                db_comment="Structured metadata: user_id, request_id, ip, url, exception, stack",
                default=dict,
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="Timestamp when log was created"
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="environment",
            field=models.CharField(
                blank=True,
                db_comment="Environment: production, staging, local",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="extra",
            field=models.JSONField(
                blank=True, db_comment="Optional extra data", default=dict
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="level",
            field=models.CharField(
                db_comment="Log level: debug, info, warning, error, critical",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="message",
            field=models.TextField(db_comment="Log message content"),
        ),
    ]
